.TH FANCY_TAR_PROGRESS 1 "March 2025" "v1.0" "User Commands"
.SH NAME
fancy_tar_progress \- create tar.gz archives with progress and extras
.SH SYNOPSIS
.B fancy_tar_progress.sh
[\-o OUTPUT] [\-n] [\-s] [\-x] file1 [file2 ...]
.SH DESCRIPTION
A fancy bash script that compresses files or folders using tar, shows a progress bar with estimated time, and supports notifications and other options.
.SH OPTIONS
.TP
.B \-o <filename>
Set the output filename. Defaults to archive.tar.gz.
.TP
.B \-n
Do not gzip. Output will be a .tar file.
.TP
.B \-s
Slow simulation mode for testing.
.TP
.B \-x
Open the containing folder after completion.
.TP
.B \-h
Show help message and exit.
.SH EXAMPLES
Compress with progress and gzip:
    fancy_tar_progress.sh -o backup.tar.gz myfolder
Compress without gzip in slow mode:
    fancy_tar_progress.sh -n -s -o backup.tar myfolder
.SH AUTHOR
Written by Jason Giambona.

